### ISSUE TITLE
Function to add more resources in one time

### ISSUE THREAD

**Issue by erik9012** [redsolver/skydroid#16]
When i want to add some new resources to skydroid its possible that i want to add a really long list what i have now. I ask for a feature that makes me able to import a .txt file with a list of resources what makes me able to add a list of 100 resources like  org.projectmaxs.module.bluetooth.fdroid-app at the same time

**Comment by redsolver** [comment]
Do you want to share this app list with other users or only use it as a personal "backup"/device-reinstall mechanism?

**Comment by erik9012** [comment]
I would like a Personal backup mechanism

**Comment by redsolver** [comment]
Ok, SkyDroid already has a "Collection" feature which can be used to add a lot of apps at once.
A future update will likely contain support for creating your own collections of apps (for example for backup purposes) and importing/exporting them.

**Comment by erik9012** [comment]
Nice. Where dan infound how exactly the collection feature works?

**Comment by redsolver** [comment]
It's explained in the README, currently you have to manually create a YAML file similar to this one:
```yaml
title: red's collection
description: This collection contains some apps
icon: sia://PAGUwiKmHy_83Att8NssAMj79PF1V8g5x_B2lKyThFhKig

apps:
  - name: org.projectmaxs.module.bluetooth.fdroid-app
  - name: noteless.redsolver
  - name: skydroid.app
```
Then create a sha256 hash, upload it https://siasky.net and update DNS records of a domain name you own.

If you have more questions or want more detailed instructions, I highly recommend joining the SkyDroid Chat: https://matrix.to/#/#skydroid:matrix.org
